"""alter user tb

Revision ID: 70b0031593bb
Revises: baaa6a97e43c
Create Date: 2022-08-30 12:05:50.213671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70b0031593bb'
down_revision = 'baaa6a97e43c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=255), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=32), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('t_category_attachment',
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('attachment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachment.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], )
    )
    op.create_table('t_post_attachment',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('attachment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachment.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], )
    )
    op.add_column('category', sa.Column('image', sa.LargeBinary(), nullable=True))
    op.add_column('category', sa.Column('timestamp', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_category_timestamp'), 'category', ['timestamp'], unique=False)
    op.add_column('post', sa.Column('cover_image', sa.LargeBinary(), nullable=True))
    op.add_column('user', sa.Column('points', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_points'), 'user', ['points'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_points'), table_name='user')
    op.drop_column('user', 'points')
    op.drop_column('post', 'cover_image')
    op.drop_index(op.f('ix_category_timestamp'), table_name='category')
    op.drop_column('category', 'timestamp')
    op.drop_column('category', 'image')
    op.drop_table('t_post_attachment')
    op.drop_table('t_category_attachment')
    op.drop_table('attachment')
    # ### end Alembic commands ###
