"""changge user tb

Revision ID: 4b8462fb4645
Revises: c9932614a7d2
Create Date: 2022-08-31 12:51:50.060849

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b8462fb4645'
down_revision = 'c9932614a7d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('answer_heart_value', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('answerids', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('dept_name', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('first_prize_level', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('first_prize_time', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('heart_value', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('is_local', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_prize', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('lottery_count', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('mobile_number', sa.String(length=16), nullable=True))
    op.add_column('user', sa.Column('second_prize_level', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('second_prize_time', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('thumbed', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('upload_comment', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('upload_file_url', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('upload_heart_value', sa.Integer(), nullable=True))
    op.drop_column('user', 'points')
    op.drop_column('user', 'draw_time')
    op.drop_column('user', 'is_draw')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_draw', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('draw_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('points', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('user', 'upload_heart_value')
    op.drop_column('user', 'upload_file_url')
    op.drop_column('user', 'upload_comment')
    op.drop_column('user', 'thumbed')
    op.drop_column('user', 'second_prize_time')
    op.drop_column('user', 'second_prize_level')
    op.drop_column('user', 'mobile_number')
    op.drop_column('user', 'lottery_count')
    op.drop_column('user', 'is_prize')
    op.drop_column('user', 'is_local')
    op.drop_column('user', 'heart_value')
    op.drop_column('user', 'first_prize_time')
    op.drop_column('user', 'first_prize_level')
    op.drop_column('user', 'dept_name')
    op.drop_column('user', 'answerids')
    op.drop_column('user', 'answer_heart_value')
    # ### end Alembic commands ###
