"""add thumed for user

Revision ID: 8e4d70e763e6
Revises: a09c3ae41471
Create Date: 2022-09-06 10:58:01.740865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e4d70e763e6'
down_revision = 'a09c3ae41471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('thumbe_times', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'thumbe_times')
    # ### end Alembic commands ###
