"""alert gift

Revision ID: 9e2902d33df8
Revises: 5560aa15faee
Create Date: 2022-09-04 11:59:33.724019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e2902d33df8'
down_revision = '5560aa15faee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_gift_allowance', table_name='gift')
    op.drop_index('ix_gift_level', table_name='gift')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_gift_level', 'gift', ['level'], unique=False)
    op.create_index('ix_gift_allowance', 'gift', ['allowance'], unique=False)
    # ### end Alembic commands ###
