"""add upload file

Revision ID: ad7473fecb48
Revises: 32555cd54c23
Create Date: 2022-09-01 14:41:42.071716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad7473fecb48'
down_revision = '32555cd54c23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('upload_file', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'upload_file')
    # ### end Alembic commands ###
