"""changge user tb1

Revision ID: b5f07b657bd0
Revises: 4b8462fb4645
Create Date: 2022-08-31 13:57:59.570404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5f07b657bd0'
down_revision = '4b8462fb4645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nick_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'nick_name')
    # ### end Alembic commands ###
