"""add gift table and riddle

Revision ID: c9932614a7d2
Revises: 70b0031593bb
Create Date: 2022-08-30 20:41:50.347204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9932614a7d2'
down_revision = '70b0031593bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('pic_name', sa.String(length=50), nullable=True),
    sa.Column('note', sa.String(length=128), nullable=True),
    sa.Column('allowance', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('pic_name')
    )
    op.create_index(op.f('ix_gift_allowance'), 'gift', ['allowance'], unique=False)
    op.create_index(op.f('ix_gift_level'), 'gift', ['level'], unique=False)
    op.create_table('riddle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.String(length=128), nullable=True),
    sa.Column('point', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('user', sa.Column('draw_time', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('gift_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('is_draw', sa.Boolean(), nullable=True))
    op.drop_index('ix_user_points', table_name='user')
    op.create_foreign_key(None, 'user', 'gift', ['gift_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_index('ix_user_points', 'user', ['points'], unique=False)
    op.drop_column('user', 'is_draw')
    op.drop_column('user', 'gift_id')
    op.drop_column('user', 'draw_time')
    op.drop_table('riddle')
    op.drop_index(op.f('ix_gift_level'), table_name='gift')
    op.drop_index(op.f('ix_gift_allowance'), table_name='gift')
    op.drop_table('gift')
    # ### end Alembic commands ###
