"""add blue

Revision ID: cbd200cdfada
Revises: 310c9f81adb8
Create Date: 2022-09-07 14:44:23.957421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbd200cdfada'
down_revision = '310c9f81adb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_blue_upload_time'), 'blue', ['upload_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blue_upload_time'), table_name='blue')
    # ### end Alembic commands ###
